// apps/vue/src/challenges/stack/index.vue
<template>
    <div class="app">
        <div>
            <input v-model="userInput" placeholder="Enter the value" style=" width: 100%;" />
            <div class="action-buttons">
                <button @click="pushItem">Push</button>
                <button @click="popItem">Pop</button>
                <button @click="peekItem">Peek</button>
                <button @click="isStackEmpty">IsEmpty</button>
                <button @click="isStackFull">IsFull</button>
            </div>
        </div>
        <hr />
        <h4 class="text-center">{{ output }}</h4>
        <ul class="text-center">
            <li v-for="(value, index) in stack" :key="index">
                {{ value }}
            </li>
        </ul>
    </div>
</template>

<script setup lang="ts">
import { ref, Ref } from 'vue'

const stack: Ref<string[]> = ref([])
const userInput: Ref<string> = ref('')
const output: Ref<string> = ref('')

function pushItem() {
    if (stack.value.length == 5) {
        output.value = 'Stack is full'
    } else if (userInput.value) {
        stack.value.push(userInput.value)
        output.value = `${userInput.value} is pushed into the Stack`
        userInput.value = ''
    } else {
        output.value = 'Please enter value first'
    }
}

function popItem() {
    if (!stack.value.length) {
        output.value = 'Stack is empty'
    } else {
        output.value = `${stack.value[stack.value.length - 1]} is popped from the Stack`
        stack.value = stack.value.slice(0, -1)
    }
}

function peekItem() {
    if (!stack.value.length) {
        output.value = 'Stack is empty'
    } else {
        output.value = `Last element is ${stack.value[stack.value.length - 1]}`
    }
}

function isStackEmpty() {
    if (!stack.value.length) {
        output.value = 'Stack is empty'
    } else {
        output.value = 'Stack is not empty'
    }
}

function isStackFull() {
    if (stack.value.length == 5) {
        output.value = 'Stack is full'
    } else {
        output.value = 'Stack is not full'
    }
}

</script>

<style scoped css="scss">
.app {
    margin: 10px auto;
    padding: 20px;
    max-width: 480px;
    border: 1px solid;
}

.app input {
    padding: 10px;
    font-size: medium;
}

ul {
    list-style-type: none;
    padding-inline-start: 0px !important
}

li {
    padding: 5px;
    margin-bottom: 10px;
    background-color: #007bff34;
    border-radius: 3px;
    font-size: medium;
}

.action-buttons {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin: 20px 0;
}

button {
    background-color: #007bff;
    color: white;
    border: none !important;
    border-radius: 3px;
    padding: 10px 20px;
}

button:hover {
    background-color: #0056b3;
}
</style>

// react/src/machine-coding/stack-implementation/Stack.jsx
import styles from './stack.module.css';
import { useState } from 'react';

const Stack = () => {
  const [stack, setStack] = useState([]);
  const [inputVal, setInputVal] = useState('');
  const [outPut, setOutPut] = useState('');

  const onChangeHandler = (e) => {
    setInputVal(e.target.value);
  };

  const pushHandler = () => {
    if (inputVal=='') {
      setOutPut(`Enter a value`);
      return;
    }
    if (stack.length === 10) {
      setOutPut('Stack is Full');
      return;
    }
    setStack([...stack, inputVal]);
    setOutPut(`${inputVal} is pushed into the Stack`);
    setInputVal('');
  };

  const popHandler = () => {
    if (!stack.length) {
      setOutPut('Stack is empty');
      return 
    }
    setStack(stack.slice(0, -1));
    setOutPut(`${stack[stack.length - 1]} is popped from the Stack `);
  };

  const peekHandler = () => {
    if (!stack.length) setOutPut('Stack is empty');
    else {
      const lastElement = stack[stack.length - 1];
      setOutPut(`Last element is ${lastElement}`);
    }
  };

  const isEmptyHandler = () => {
    if (stack.length === 0) {
      setOutPut('Stack is empty');
    } else {
      setOutPut('Stack is not empty');
    }
  };

  const isFullHandler = () => {
    // console.log('isFullHandler');
    if (stack.length === 10) {
      setOutPut('Stack is Full');
    } else {
      setOutPut('Stack is not full');
    }
  };

  return (
    <div className={styles.container}>
      <div className={styles.stack}>
        <input type="text" placeholder='Enter a value' value={inputVal} onChange={onChangeHandler} required />

        <div className={styles.btn_root}>
          <button onClick={pushHandler}>Push</button>
          <button onClick={popHandler}>Pop</button>
          <button onClick={peekHandler}>Peek</button>
          <button onClick={isEmptyHandler}>IsEmpty</button>
          <button onClick={isFullHandler}>IsFull</button>
        </div>
        <hr />

        <h3>{outPut}</h3>

        {stack.slice().reverse().map((element, index) => {
          return (
           <div key={index} className={styles.stackElement}>
           <p>{element}</p>
           </div>
          );
         })}

      </div>
    </div>
  );
};

export default Stack;
