// apps/angular/src/app/challenges/stack/stack.component.ts
import { Component } from '@angular/core';

import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-stack',
  imports: [FormsModule],
  templateUrl: './stack.component.html',
  styleUrls: ['./stack.component.scss'],
})
export class StackComponent {
  stack: string[] = [];
  inputVal = '';
  outPut = '';

  push() {
    this.stack = [...this.stack, this.inputVal];
    this.inputVal = '';
  }

  pop() {
    this.stack = this.stack.slice(0, -1);
  }

  peek() {
    if (!this.stack.length) {
      this.outPut = 'Stack is empty';
    } else {
      const lastElement = this.stack[this.stack.length - 1];
      this.outPut = `Last element is ${lastElement}`;
    }
  }

  isEmpty() {
    if (this.stack.length === 0) {
      this.outPut = 'Stack is empty';
    } else {
      this.outPut = 'Stack is not empty';
    }
  }

  isFull() {
    if (this.stack.length === 5) {
      this.outPut = 'Stack is Full';
    } else {
      this.outPut = 'Stack is not Full';
    }
  }
}

<div class="container">
    <div class="stack">
        <input type="text" name="inputVal" [(ngModel)]="inputVal" required />

        <div class="btn_root">
            <button (click)="push()">Push</button>
            <button (click)="pop()">Pop</button>
            <button (click)="peek()">Peek</button>
            <button (click)="isEmpty()">IsEmpty</button>
            <button (click)="isFull()">IsFull</button>
        </div>
        <hr />

        <h3>{{outPut}}</h3>

        <div class="stackElement" *ngFor="let element of stack">
            <p>{{element}}</p>
        </div>
    </div>
</div>

// react/src/machine-coding/stack-implementation/Stack.jsx
import styles from './stack.module.css';
import { useState } from 'react';

const Stack = () => {
  const [stack, setStack] = useState([]);
  const [inputVal, setInputVal] = useState('');
  const [outPut, setOutPut] = useState('');

  const onChangeHandler = (e) => {
    setInputVal(e.target.value);
  };

  const pushHandler = () => {
    setStack([...stack, inputVal]);
    setInputVal('');
  };

  const popHandler = () => {
    setStack(stack.slice(0, -1));
  };

  const peekHandler = () => {
    if (!stack.length) setOutPut('Stack is empty');
    else {
      const lastElement = stack[stack.length - 1];
      setOutPut(`Last element is ${lastElement}`);
    }
  };

  const isEmptyHandler = () => {
    if (stack.length === 0) {
      setOutPut('Stack is empty');
    } else {
      setOutPut('Stack is not empty');
    }
  };

  const isFullHandler = () => {
    // console.log('isFullHandler');
    if (stack.length === 5) {
      setOutPut('Stack is Full');
    } else {
      setOutPut('Stack is not full');
    }
  };

  return (
    <div className={styles.container}>
      <div className={styles.stack}>
        <input type="text" value={inputVal} onChange={onChangeHandler} required />

        <div className={styles.btn_root}>
          <button onClick={pushHandler}>Push</button>
          <button onClick={popHandler}>Pop</button>
          <button onClick={peekHandler}>Peek</button>
          <button onClick={isEmptyHandler}>IsEmpty</button>
          <button onClick={isFullHandler}>IsFull</button>
        </div>
        <hr />

        <h3>{outPut}</h3>

        {stack?.map((element, index) => {
          return (
            <div key={index} className={styles.stackElement}>
              <p>{element}</p>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default Stack;
