// angular/src/app/components/challenge/challenge.component.ts
import { Component, Input } from '@angular/core';

import { Challenge } from 'src/app/types/interfaces/challenge.intf';
import { contributors } from 'src/app/helpers/contributors';

@Component({
  selector: 'app-challenge',
  templateUrl: './challenge.component.html',
  styleUrls: ['./challenge.component.scss'],
})
export class ChallengeComponent {
  @Input() challenge!: Challenge;
  public contributors = contributors;
}

<a ngClass="challengeCard" [routerLink]="'machine-coding/' + challenge.link">
  <span *ngIf="challenge.isNew" class="new">New</span>
  <div>
    <h3>{{ challenge.title }}</h3>

    <div *ngIf="challenge.developer" class="developer">
      <img [src]="contributors.get(challenge.developer)?.pic" alt="" />
      <span class="name">{{
        contributors.get(challenge.developer)?.name
      }}</span>
    </div>
  </div>
</a>

// apps/host/src/components/modules/challenges/challenge-grid/challenge.tsx
import type { IChallenge, IContributor } from '@fmc/data/types';

import { AvatarGroup } from '../avatar/avatar';
import styles from './challenge-grid.module.scss';

interface Props {
  link: string;
  contributor?: IContributor;
  challenge: IChallenge;
  techImg: string;
}

const Challenge = ({ link, contributor, challenge }: Props) => {
  return (
    <a
      key={challenge.title}
      className={`${styles.challengeCard} ${styles[challenge.difficulty]} ${challenge.isNew && styles.new}`}
      href={link}
    >
      {challenge.isNew && <div className={styles.newTag}>NEW</div>}
      <div className="flex-space-between">
        <div className="flex-space-between">
          {/* <div>
            <img src={techImg} alt={'alt'} width="30px" />
          </div> */}
          <h3>{challenge.title}</h3>
        </div>
        <div className={styles.difficultyBadge}>
          <div className={styles.ellips} />
          {challenge.difficulty}
        </div>
      </div>
      <div className="flex-space-between">
        <div className="flex-space-between">
          {challenge.developer && (
            <div className={styles.developer}>
              <img src={`${contributor?.pic}?v=4&s=75`} alt="" />
              <span className={styles.name}>{contributor?.name}</span>
            </div>
          )}
          <div>
            {challenge.contributors && <AvatarGroup contributorNames={challenge.contributors} />}
          </div>
        </div>
        {challenge.tags!.find((e) => e === 'interview') && (
          <div className={styles.interviewBadge}>Interview</div>
        )}
      </div>
    </a>
  );
};

export default Challenge;
