// vue/src/pages/challenges.vue
<template>
  <Navbar>
    <a href="/frontend-mini-challenges/native">JavaScript Mini Challenges</a>
    <a href="/frontend-mini-challenges/react/dist/#/challenges">React Mini Challenges</a>
  </Navbar>

  <div className="container text-center">
    <ChallengeGrid />
  </div>
</template>

<script setup lang="ts">
import ChallengeGrid from '@/components/ChallengeGrid.vue';
import Navbar from '@/components/Navbar.vue';
</script>

// react/src/pages/Challenges.tsx
import ChallengeGrid from '@/components/challenges/ChallengeGrid';
import Navbar from '@/components/navbar/Navbar';

function App() {
  return (
    <>
      <Navbar>
        <a href="/frontend-mini-challenges/native">JavaScript Mini Challenges</a>
        <a href="/frontend-mini-challenges/vue/dist/#/">VueJs Mini Challenges</a>
      </Navbar>

      <div className="container text-center">
        <ChallengeGrid />
      </div>
    </>
  );
}

export default App;
