// apps/angular/src/app/challenges/word-count/word-count.component.ts
import { Component } from '@angular/core';

import { FormsModule } from '@angular/forms';

interface WordCountModel {
  text: string;
  wordCount: number;
  charCount: number;
  paraCount: number;
}

@Component({
  selector: 'app-word-count',
  imports: [FormsModule],
  templateUrl: './word-count.component.html',
  styleUrls: ['./word-count.component.scss'],
})
export class WordCountComponent {
  text = '';
  wordCount = 0;
  charCount = 0;
  paraCount = 0;

  saveData({ text, wordCount, charCount, paraCount }: WordCountModel) {
    localStorage.setItem('text', text);
    localStorage.setItem('words', wordCount + '');
    localStorage.setItem('chars', charCount + '');
    localStorage.setItem('paras', paraCount + '');
  }

  countWords() {
    const words = this.text.split(/\s+/).filter((word) => word !== '');
    const characters = this.text.length;
    const paragraphs = this.text.split('\n').filter((para) => para.trim() !== '').length;

    this.wordCount = words.length;
    this.charCount = characters;
    this.paraCount = paragraphs;

    // Update data
    this.saveData({
      text: this.text,
      wordCount: this.wordCount,
      charCount: this.wordCount,
      paraCount: this.paraCount,
    });
  }

  clearText() {
    this.text = '';
    this.wordCount = 0;
    this.charCount = 0;
    this.paraCount = 0;
  }

  loadData() {
    this.text = localStorage.getItem('text') || '';
    this.wordCount = +(localStorage.getItem('words') || 0);
    this.charCount = +(localStorage.getItem('chars') || 0);
    this.paraCount = +(localStorage.getItem('paras') || 0);
  }
}

<div class="container">
  <textarea id="text-input" placeholder="Enter your text here..." [(ngModel)]="text"
    [ngModelOptions]="{updateOn: 'change'}">
  </textarea>
  <div class="controls">
    <div id="word-count">Words: {{wordCount}}</div>
    <div id="char-count">Chars: {{charCount}}</div>
    <div id="para-count">Paras: {{paraCount}}</div>
    <button id="count-button" (click)="countWords()">
      Count
    </button>
    <button id="clear-button" (click)="clearText()">
      Clear
    </button>
  </div>
</div>

// react/src/machine-coding/word-count/index.jsx
// WordCounter.js

import React, { useEffect, useRef, useState } from 'react';

import styles from './styles.module.scss';

const saveData = ({ text, wordCount, charCount, paraCount }) => {
  localStorage.setItem('text', text);
  localStorage.setItem('words', wordCount);
  localStorage.setItem('chars', charCount);
  localStorage.setItem('paras', paraCount);
};

function WordCounter() {
  const [text, setText] = useState('');
  const [wordCount, setWordCount] = useState(0);
  const [charCount, setCharCount] = useState(0);
  const [paraCount, setParaCount] = useState(0);
  const firstLoad = useRef(true);

  useEffect(() => {
    loadData();
  }, []);

  useEffect(() => {
    if (firstLoad.current) {
      firstLoad.current = false;
      return;
    }
    saveData({ text, wordCount, charCount, paraCount });
  }, [text, wordCount, charCount, paraCount]);

  const countWords = () => {
    const words = text.split(/\s+/).filter((word) => word !== '');
    const characters = text.length;
    const paragraphs = text.split('\n').filter((para) => para.trim() !== '').length;

    setWordCount(words.length);
    setCharCount(characters);
    setParaCount(paragraphs);
  };

  const clearText = () => {
    setText('');
    setWordCount(0);
    setCharCount(0);
    setParaCount(0);
  };

  const loadData = () => {
    setText(localStorage.getItem('text') || '');
    setWordCount(localStorage.getItem('words') || 0);
    setCharCount(localStorage.getItem('chars') || 0);
    setParaCount(localStorage.getItem('paras') || 0);
  };

  return (
    <div className={styles.container}>
      <textarea
        id="text-input"
        placeholder="Enter your text here..."
        value={text}
        onChange={(e) => setText(e.target.value)}
      ></textarea>
      <div className={styles.controls}>
        <div id="word-count">Words: {wordCount}</div>
        <div id="char-count">Chars: {charCount}</div>
        <div id="para-count">Paras: {paraCount}</div>
        <button id="count-button" onClick={countWords}>
          Count
        </button>
        <button id="clear-button" onClick={clearText}>
          Clear
        </button>
      </div>
    </div>
  );
}

export default WordCounter;
