// angular/src/app/machine-coding/todo/list/list.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-todo-list',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './list.component.html',
  styleUrls: ['./list.component.scss'],
  // changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ListComponent {
  // TODO; change type of list
  @Input() items: any[] = [];
  @Output() edit = new EventEmitter();
  @Output() delete = new EventEmitter();
}

<li class="item" *ngFor="let item of items; let idx=index;">
    <span>{{item.value}}</span>
    <div>
        <button class="editBtn" (click)="edit.emit(item)">
            Edit
        </button>
        <button class="deleteBtn" (click)="delete.emit(idx)">
            Delete
        </button>
    </div>
</li>

// react/src/machine-coding/todo-list/list.jsx
import styles from "./todo.module.scss";

function List({ items, handleEditClick, handleDeleteClick }) {
  return items.map((item, idx) => (
    <li className={styles.item} key={item.id}>
      <span>{item.value}</span>
      <div>
        <button
          className={styles.editBtn}
          onClick={() => handleEditClick(item)}
        >
          Edit
        </button>
        <button
          className={styles.deleteBtn}
          onClick={() => handleDeleteClick(idx)}
        >
          Delete
        </button>
      </div>
    </li>
  ));
}

export default List;
